//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proiect1_3
{
    using System;
    using System.Collections.Generic;
    
    public partial class People
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int PhotosId { get; set; }
    
        public virtual Photos Photo { get; set; }
    }
}
